%.pdf: %.py
	python get_screenshot.py $<

default: first.pdf\
	Square_Basic.pdf Square_Loop.pdf polygon.pdf \
	spiral.pdf \
	circles.pdf \
	chess.pdf chess_2.pdf \
	more_circles.pdf \
	face.pdf \
	
	
#	Square_Event.pdf 
 